#reset global variables.
reset;

#define all the variable.
var x1 >=0 integer;
var x2 >=0 integer;
var x3 >=0 integer;
var x4 >=0 integer;

#define our objective function
minimize z: x1+x2+x3+x4;

#define our constrains
s.t. c1: x1 +x2>=1;
s.t. c2: x2 +x3>=1;
s.t. c3: x2 +x4>=1;
s.t. c4: x3 +x4>=1;

#selectice the package to solve our problem
option solver cplex;

#solving the LPP
solve;

#displaying the results
display x1,x2,x3,x4,z;